### ISSUE TITLE
Error when passing specific names to addCohortIntersect

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#235]
As below, if I try and pass a specific name to addCohortIntersectFlag I'm getting an error. I think this behaviour should be allowed - when I'm creating one variable to just choose a specific name myself. @catalamarti what do you think?

``` r
library(PatientProfiles)
cdm <- mockPatientProfiles()
# default naming
cdm$cohort1 %>%
  addCohortIntersectFlag(
    cdm = cdm,
    indexDate = "cohort_start_date",
    targetCohortTable = "cohort2",
    window = c(-Inf, -1)
  )
#> # Source:   table<dbplyr_006> [4 x 7]
#> # Database: DuckDB 0.7.1 [eburn@Windows 10 x64:R 4.2.1/:memory:]
#>   cohort_definition_id subject_id cohort_start_date cohort_end_date
#>                  <dbl>      <dbl> <date>            <date>         
#> 1                    1          1 2020-01-01        2020-04-01     
#> 2                    1          1 2020-06-01        2020-08-01     
#> 3                    1          2 2020-01-02        2020-02-02     
#> 4                    2          3 2020-01-01        2020-03-01     
#> # ℹ 3 more variables: cohort_1_minf_to_m1 <dbl>, cohort_2_minf_to_m1 <dbl>,
#> #   cohort_3_minf_to_m1 <dbl>
# specific name
cdm$cohort1 %>%
  addCohortIntersectFlag(
    cdm = cdm,
    indexDate = "cohort_start_date",
    targetCohortTable = "cohort2",
    window = c(-Inf, -1),
    nameStyle = "event_in_washout"
  )
#> Error in "cli_text(..., .envir = .envir)": ! Could not evaluate cli `{}` expression: `id_name`.
#> Caused by error in `eval(expr, envir = envir)`:
#> ! object 'id_name' not found
```

<sup>Created on 2023-05-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by catalamarti** [comment]
Yes, this should work. Can you take a look @KimLopezGuell ?

**Comment by KimLopezGuell** [comment]
So, what is happening here is that 
          cdm <- mockPatientProfiles()
creates a cohort2 with cohort_definition_id %in% c(1:3), and addCohortIntersectFlag tries to create three different columns but cannot do that with different names if the style is "event_in_washout". If you do, for example, instead:
          cdm$cohort1 %>%
            addCohortIntersectFlag(
              cdm = cdm,
              indexDate = "cohort_start_date",
              targetCohortTable = "cohort2",
              window = c(-Inf, -1),
              nameStyle = "event_in_washout_{id_name}"
            )
it works.
I am not sure what we should do. Make the error more informative? Or is there any functionality that you find missing, then? 
@edward-burn @catalamarti

**Comment by catalamarti** [comment]
If this is the case maybe we can have a more appropriate error, but I would say is that the behaviour is the correct one. @edward-burn @KimLopezGuell

**Comment by edward-burn** [comment]
Ah ok, makes sense! I suppose one question is what the behaviour should be when a user has a cohort table with three cohorts but does not specify a cohort idea. So now we create multiple variables, one for each cohort, but perhaps a user who does not properly read the documentation (like me) might expect one variable with cohort id ignored and all people considered together.

I kind of feel like the current implementation is the right one, but maybe this could be an option?

**Comment by KimLopezGuell** [comment]
I agree that this could be an option. If a user has multiple cohorts of different conditions and wants to washout on all of them... how likely is this to happen?

**Comment by catalamarti** [comment]
to check @KimLopezGuell

**Comment by catalamarti** [comment]
@KimLopezGuell could you take a look?
