### ISSUE TITLE
Use temporary instead of tablePrefix

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#236]
Now that CDMConnector allows for the write_prefix attribute, we can change `tablePrefix` to `temporary` (ie the same change as done in the latest version of IncidencePrevalence https://github.com/darwin-eu/IncidencePrevalence/commit/0df2185ed35d2d320014ba551f2362e3fbb9d878

@catalamarti I'm happy to work on this if you want to assign it to me?

**Comment by edward-burn** [comment]
As discussed, we'll remove tablePrefix and not have a temporary agument. Instead we'll use the write_prefix attribute for now (if filled in permanent tables will be created using it, otherwise temporary tables will be used). If this is implemented https://github.com/darwin-eu-dev/CDMConnector/issues/153, we would then instead use the intermediateAsTemporary attribute

**Comment by catalamarti** [comment]
I close this issue till we solve the CDMConnector one
