### ISSUE TITLE
PaRe report

### ISSUE THREAD

**Issue by mvankessel-EMC** [darwin-eu-dev/PatientProfiles#239]
I'll share the html-file with @edward-burn shortly after posting, as I can't upload it here.

## Package overview
![image](https://github.com/oxford-pharmacoepi/PatientProfiles/assets/112690347/693f29bf-a35f-40f8-a0e2-433c0a082a27)
`addIntersect`, `checkCohortNames`, `addDemographics`, and `checkCdm` seem like the most pivotal functions in the package. `addIntersect` and `addDemographcis` have >1000 lines of tests. I did not see any tests for `checkCohortNames` and `checkCdm` on main.

### Zoom in on pivotal functions
_*Manually added_

![image](https://github.com/oxford-pharmacoepi/PatientProfiles/assets/112690347/e10507df-52ef-472e-bb60-68a5544689ab)

![image](https://github.com/oxford-pharmacoepi/PatientProfiles/assets/112690347/1e5854f6-7271-491c-9f57-0391d174f565)

![image](https://github.com/oxford-pharmacoepi/PatientProfiles/assets/112690347/c1d28a31-36ff-4604-bab7-f030e2091808)

![image](https://github.com/oxford-pharmacoepi/PatientProfiles/assets/112690347/576adccb-a4ab-42ba-a7f9-e74b3d367f8c)

`addIntersect` has alot of functions calling it, but it also calls several functions. `checkCohortNames` is an endpoint of other functions that call it. `addDemographics` is in a similar situation to _addInmtersect_.
`checkCdm` is also an endpoint like _checkCohortNames_, but with significantly more calls to it.

## Function Summary Statistics
min | median | max
-- | -- | --
Number of arguments | 1 | 2 | 4
Lines of code | 5 | 24 | 643
Cyclomatic complexity | 1 | 2 | 50

![image](https://github.com/oxford-pharmacoepi/PatientProfiles/assets/112690347/9022bdb8-a9f2-4b69-907a-6270c097241d)

In general I'd say the package is in a maintainable state, with some outliers that could use some work.

## Cyclomatic Complexity and Function Size
Function | Number of arguments | Lines of code | Cyclomatic complexity | Location
-- | -- | -- | -- | --
mockPatientProfiles | 2 | 643 | 50 | mockPatientProfiles.R (from line: 51)
addIntersect | 2 | 330 | 32 | addIntersect.R (from line: 93)
addDemographics | 2 | 227 | 23 | addDemographics.R (from line: 42)
addCategories | 2 | 84 | 19 | addCategories.R (from line: 53)

`mockPatientProfiles` is the biggest offender of both complexity and line size. If this function entails just mock data and not direct functionality of the package, I do not think it has the highest priority, and instead would focus on `addIntersect` and `addDemographics`. Like mentioned before these two functions seem well tested, but I think it would be nice to drive complexity down and size a bit.

Interestingly the size of `addCategories` seems relatively small for it's complexity.

## Lintr
type | Percentage of lines assessed
-- | --
style | 7.35
warning | 2.83

Overall Lintr doesn't seem to pick up that many things, I think warnings should be driven down to preferably <1.

### Top 10 Warnings
message | n
-- | --
Conditional expressions require scalar logical operators (&& and \|\|) | 14
no visible binding for global variable '.env' | 10
no visible global function definition for ':=' | 10
no visible global function definition for 'checkCdm' | 8
no visible global function definition for 'addIntersect' | 5
no visible global function definition for 'checkCohortNames' | 5
no visible global function definition for 'checkSnakeCase' | 5
no visible global function definition for 'checkVariableInX' | 5
1:length(...) is likely to be wrong in the empty edge case. Use seq_along(...) instead. | 4
no visible global function definition for 'checkX' | 4

### Top 10 Style Messages
message | n
-- | --
Variable and function name style should be camelCase. | 99
Lines should not be more than 80 characters. | 63
Commas should always have a space after. | 15
Commented code should be removed. | 9
Place a space before left parenthesis, except in a function call. | 8
Closing curly-braces should always be on their own line, unless they are followed by an else. | 5
Opening curly braces should never go on their own line and should always be followed by a new line. | 5
Put spaces around all infix operators. | 4
There should be a space before an opening curly brace. | 2
There should be a space between a right parenthesis and a body expression. | 2

### Dependency Graph Statistics compared to other packages
package | Lines R | countVertices | countEdges | meanDegree | meanDistance
-- | -- | -- | -- | -- | --
PatientProfiles [0.1.0] | 2965 | 251 | 1149 | 9.16 | 2.82
IncidencePrevalence [0.2.0] | 4547 | 271 | 1214 | 8.96 | 2.85
Capr [2.0.2] | 3364 | 195 | 860 | 8.82 | 2.72
DrugUtilisation [0.1.1] | 6010 | 173 | 832 | 9.62 | 2.73

_*Manually added comparisons_

The dependencies imported seem to have a lot of recursive dependencies. Even though there are only 10 direct imports. This is most likely due to the 11 suggested packages.

### Dependency usage
![image](https://github.com/oxford-pharmacoepi/PatientProfiles/assets/112690347/22c63f9b-9deb-4c73-b4b7-708c424ffbc0)

The package `tibble` could be dropped, as the function `tibble` is also exported from `dplyr`.

I am assuming `mockPatientProfiles` is optional, as it uses `duckdb` from the suggested packages

The `glue` package seems to be used in the following places:
file | line | pkg | fun
-- | -- | -- | --
addDemographics.R | 273 | glue | glue
addDemographics.R | 281 | glue | glue
addDemographics.R | 285 | glue | glue
addDemographics.R | 290 | glue | glue
addDemographics.R | 294 | glue | glue
addDemographics.R | 297 | glue | glue
addDemographics.R | 301 | glue | glue
addDemographics.R | 304 | glue | glue
addIntersect.R | 394 | glue | glue
checks.R | 49 | glue | glue
checks.R | 200 | glue | glue

I am assuming the functions defined at those places are not optional functionality.

**Comment by edward-burn** [comment]
This is fantastic @mvankessel-EMC! Really appreciate your work on PaRe as it highlights all these things we can improve  @catalamarti let's please take a look and open related issues to address things for the v0.2 release

**Comment by catalamarti** [comment]
@mvankessel-EMC @edward-burn I close this issue as most of the issues were solved. I will rerun PaRe report and put it on a vignette
