### ISSUE TITLE
Output of summariseCharacteristics

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/PatientProfiles#257]
Currently the columns of the output are: "strata_name", "strata_level", "variable", "variable_classification", "estimate", "value"

This fits very well when we want the mean of a daily dose for example:
```
"strata_name", "strata_level", "variable",     "variable_classification", "estimate",     "value"
"age",         "<18",          "daily_dose",   "numeric",                 "mean",         "20"
```

But when we have a categorical variable for example:
```
"strata_name", "strata_level", "variable",     "variable_classification", "estimate",     "value"
"age",         "<18",          "sex",          "categorical",             "Male: count",  "11"
```

Do we want to change the format in any way/ @edward-burn

**Comment by edward-burn** [comment]
suggested required summarise* function outputs:
strata_name; strata_level: variable_name; variable_level; variable_type; estimate_type; estimate

Let's see if this is possible. If so, we could then create a "summarisedResult" class

**Comment by catalamarti** [comment]
How should we name the function? @edward-burn 
createSummary? summariseData? ...

**Comment by edward-burn** [comment]
I would say the eventual class could be "summarisedResult" (and we could have another one "estimatedResult" for IncidencePrevalence etc). 

For cohort_name, could this be made more general (as we might summarise things other than cohorts)? For CodelistGenerator we have "group_name" and "group_level" https://github.com/darwin-eu/CodelistGenerator/blob/d27aaf5662aedd5f33b203d9f884d232fd1290b2/tests/testthat/test-summariseCodeUse.R#L32 We could have the group name as "cohort" and group level as "cohort name X"? 

At the moment, in IncidencePrevalence has cdm_name in the output so we could stick with that https://github.com/darwin-eu-dev/IncidencePrevalence/blob/a03cb4256ce6fce699d626dad7fa2efce8574aa0/tests/testthat/test-estimateIncidence.R#L43. And we can also add the package name and version here too
