### ISSUE TITLE
Error could not find function "addCohortIntersectFlag"

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/PatientProfiles#291]
i was just working through the vignette and in the cohort intersection part, 
I got the error that the function "addCohortIntersectFlag" was not found

**Comment by tiozab** [comment]
I used now PatientProfiles::addCohortIntersectFlag instead and then I get another error:
Error: 'addCohortIntersectFlag' is not an exported object from 'namespace:PatientProfiles'

**Comment by catalamarti** [comment]
Hi @tiozab I guess that you were able to solve this right? You need to install the last version of PatientProfiles
