### ISSUE TITLE
small error when doing the cohort_count

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/PatientProfiles#297]
https://github.com/darwin-eu-dev/PatientProfiles/blob/724ed1d75942de9769bddc28cdf143ad9cf581f7/vignettes/articles/ExampleAnalysis.Rmd#L111

use select() instead of group_by()
otherwise we do not get the number of subjects but the number of records

**Comment by catalamarti** [comment]
Thanks for reporting @tiozab solved in #302
