### ISSUE TITLE
address problems with long names in summariseCharacteristics

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/PatientProfiles#311]

**Comment by catalamarti** [comment]
My idea would be that in summariseCharacteristics we can name all the columns as column_01, column_02, column_03, and change the names latter in the summary.  Then no warning or error is needed.
The problem is with the add functions. I believe that a warning should be the adequate behavior. In fact I think that this is automatically displayed when computing.

**Comment by edward-burn** [comment]
I think the problem is that the user will have subsequent code that tries to use specific names for subsequent analysis steps which would then break (e.g. it might work on their local db but not on a data partners)

**Comment by edward-burn** [comment]
For summariseCharacteristics, I suppose the code could take care of this by shortening names internally and then making them long again in the output?

**Comment by catalamarti** [comment]
#396
