### ISSUE TITLE
Error in summariseResult function

### ISSUE THREAD

**Issue by MimiYuchenGuo** [darwin-eu-dev/PatientProfiles#316]
Error in unique(formats$format_key): object 'formats' not found

this line: 
https://github.com/darwin-eu-dev/PatientProfiles/blob/bd0031b47dccd197c718cfbcb4ee60187d277c4d/R/summariseResult.R#L74

lead to this line:
https://github.com/darwin-eu-dev/PatientProfiles/blob/bd0031b47dccd197c718cfbcb4ee60187d277c4d/R/checks.R#L463C42-L463C49

"formats" variable used without definition.

**Comment by catalamarti** [comment]
It is an internal data set. If you use
`devtools::load_all()`
You should have access to it

**Comment by catalamarti** [comment]
any update @MimiYuchenGuo ?

**Comment by MimiYuchenGuo** [comment]
All good
