### ISSUE TITLE
month and day of birth are not required fields in the omop cdm

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/PatientProfiles#317]
@ilovemane can you check that addDemographics works even if this two columns are not present?

**Comment by catalamarti** [comment]
@ilovemane do you think you can take a look to this one?

**Comment by ilovemane** [comment]
it works!
cdm <- OmopMocker::mockCdm(nPerson = 100) |> OmopMocker::generateSyntheticCohortSet()

cdm <- CDMConnector::copy_cdm_to(con = DBI::dbConnect(duckdb::duckdb(), ":memory:"),
                          schema = "main", cdm = cdm, overwrite = TRUE)


cdm$person <- cdm$person |> mutate(month_of_birth = NA,
                                   day_of_birth = NA,
                                   month_of_birth = as.character(month_of_birth),
                                   day_of_birth = as.character(day_of_birth))

cdm$cohort |> PatientProfiles::addAge()

```
# Source:   table<dbplyr_001> [?? x 5]
# Database: DuckDB v0.9.2 [miked@Windows 10 x64:R 4.3.2/:memory:]
   cohort_definition_id subject_id cohort_start_date cohort_end_date   age
                  <int>      <int> <date>            <date>          <dbl>
 1                    1          1 2004-03-17        2004-10-29          7
 2                    1          1 2004-10-30        2005-10-29          7
 3                    1          2 1997-07-06        1997-08-09         34
 4                    1          6 1986-02-04        1993-11-10         25
 5                    1          7 1996-05-17        2004-12-01         10
 6                    1         10 2003-08-21        2007-12-10          5
 7                    1         13 1999-06-10        1999-06-29         11
 8                    1         13 1999-06-30        1999-09-07         11
 9                    1         14 1981-03-30        1982-05-28          4
10                    1         14 1982-05-29        2003-02-06          5


```
