### ISSUE TITLE
CDMConnector v1.1. reverse dependency checks

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#321]
There were a few failing tests when I sent CDMConnector v1.1 to CRAN.
You'll likely get an email from them asking you to fix these. Happy to help if needed.

<img width="1680" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/10227522/634e1dea-eeea-4a1c-bc3a-8256d91b3338">

**Comment by catalamarti** [comment]
#326
