### ISSUE TITLE
summariseResult - doing more on the database side

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#322]
It would be nice if we could explore a way to get more of summariseResult done on the database side, as this is important if we have a particularly big cohort or many cohorts we want to summarise at the same time.

**Comment by edward-burn** [comment]
@catalamarti to start with we could do things on the DB side if the user only wants count and %?

**Comment by ilovemane** [comment]
I been trying to make getNumericValues to run inside database and found one really weird one. 


if you run below if x is a tibble in local 
```
x %>%
          dplyr::summarise(dplyr::across(
            .cols = dplyr::all_of(variablesFunction),
            .fns = getFunctions(functions[k]),
            .names = "{.col}"
          ))

```

it return

```

# A tibble: 1 x 4
  strata_level   age prior_observation future_observation
  <chr>        <dbl>             <dbl>              <dbl>
1 Overall       25.5              4745              22038

```

If is inside database (duckdb) it return below, for some reason it name the colnum  .names = "{.col}_{.fn}". I think is usually these naming difference that causing differences if run inside database.

```

 Source:   SQL [1 x 4]
# Database: DuckDB 0.8.1 [miked@Windows 10 x64:R 4.3.1/:memory:]
  strata_level age_median prior_observation_median future_observation_median
  <chr>             <dbl>                    <dbl>                     <dbl>
1 Overall            25.5                     4745                     22038

```

**Comment by catalamarti** [comment]
agreed to work with {.col}_{.fn} naming
