### ISSUE TITLE
Suppress count for percentage

### ISSUE THREAD

**Issue by MimiYuchenGuo** [darwin-eu-dev/PatientProfiles#323]
@catalamarti Currently the percentage of counts are NOT suppressed, but requested by @xjq8065524 to display as NA.

**Comment by catalamarti** [comment]
From now on we are going to suppress everything in cohorts smaller than minCellCount. Do not display mean, median or percentage for any variable if the size of the cohort is < minCellCount.


Tagging @ajoedicke @daniprietoalhambra @edward-burn @xjq8065524 @albertpratsu @Xintong-Li-ZnCu if you want to complain

**Comment by edward-burn** [comment]
> From now on we are going to suppress everything in cohorts smaller than minCellCount. Do not display mean, median or percentage for any variable if the size of the cohort is < minCellCount.
> 
> Tagging @ajoedicke @daniprietoalhambra @edward-burn @xjq8065524 @albertpratsu @Xintong-Li-ZnCu if you want to complain

Agree with this
