### ISSUE TITLE
Large scale characterisation format

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/PatientProfiles#346]
Hi @edward-burn @ilovemane @MimimimiGuo @KimLopezGuell 

I have been working in a new version of `summariseLargeScaleCharacteristics` that:
- Is 40% faster
- Uses permanent tables that are overwritten and dropped at the end, so we dont fill the database
- It works for standard concept, source concept and ATC codes. (To be implemented ICD10)

See #345 

So this issue is to discuss the output format currently it is:
`result_type, cdm_name, group_name, group_level, strata_name, strata_level, table_name, type, analysis, window_name, concept, concept_name, estimate_type, estimate`
As you can see there is no variable, variable_level, then we have different options:
- variable = concept_name, variable_level = window_name, extra columns: table_name, type, analysis, concept.
- variable = concept_name, variable_level = NA, extra columns: window_name, table_name, type, analysis, concept.
- We leave at it is and we dont include variable column in this case.

Happy to hear you thoughts

**Comment by edward-burn** [comment]
@catalamarti can you put some example output just to see what it looks like?

**Comment by catalamarti** [comment]
![image](https://github.com/darwin-eu-dev/PatientProfiles/assets/18575244/bd54a264-55ea-4a35-89f0-3a557a4347ab)

**Comment by edward-burn** [comment]
I would vote for your first option

**Comment by catalamarti** [comment]
Happy with that

**Comment by catalamarti** [comment]
#359
