### ISSUE TITLE
Large scale characteristics reexport

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/PatientProfiles#347]
Hi @edward-burn @ilovemane @MimimimiGuo @KimLopezGuell 

What do we want to do with the LSC in DUS? I would reexport it from PP the same way that we reexport `summariseCharacteristics`.

Are you happy with this?

**Comment by edward-burn** [comment]
I would prefer that LSC belongs to PP. Happy to re-export, but we should also think about this as it may become confusing to users. In the end they can call PP itself in study code.

**Comment by catalamarti** [comment]
As it was part of DUS initially I think it would make sense to re-export
