### ISSUE TITLE
Reducing number of computes in addIntersect

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#352]
At the moment addIntersect creates 8 temp tables when getting flag variables. @catalamarti is there any way this could be reduced? This can become problematic if running large scale studies (the alternative could be to make use of permanent tables default)

``` r
library(CDMConnector)
#> Warning: package 'CDMConnector' was built under R version 4.2.3
library(PatientProfiles)

cdm <- mockPatientProfiles()
cdm$person %>% head(2) %>% computeQuery()
#> # Source:   table<dbplyr_001> [1 x 5]
#> # Database: DuckDB 0.8.1 [eburn@Windows 10 x64:R 4.2.1/:memory:]
#>   person_id gender_concept_id year_of_birth month_of_birth day_of_birth
#>       <int> <chr>                     <dbl>          <dbl>        <dbl>
#> 1         1 8507                       1994              1           30

result <- cdm$cohort1 %>%
  addIntersect(tableName = "cohort2", value = "flag") 

cdm$person %>% head(2) %>% computeQuery()
#> # Source:   table<dbplyr_009> [1 x 5]
#> # Database: DuckDB 0.8.1 [eburn@Windows 10 x64:R 4.2.1/:memory:]
#>   person_id gender_concept_id year_of_birth month_of_birth day_of_birth
#>       <int> <chr>                     <dbl>          <dbl>        <dbl>
#> 1         1 8507                       1994              1           30
```

<sup>Created on 2023-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by catalamarti** [comment]
I would:
- make use of permanent tables
- probably some tables computes are not necessary
Is that fine with you?

**Comment by edward-burn** [comment]
Yes, and if we solve #353 then in large scale studies we can use the permanent table approach.

I'm just wondering if at some point we should always use permanent tables for this type of function (as it will often take running a large scale study for the user to find problems with temp tables). Well that's a wider consideration so the above sounds good to me for now at least

**Comment by catalamarti** [comment]
The problem of this is that then we have to require always a write_schema, we would need to align with Adam on this

**Comment by catalamarti** [comment]
#360

**Comment by catalamarti** [comment]
I have the feeling that we should discuss this a little bit before pushing this forward because the write_schema becomes a mandatory parameter
