### ISSUE TITLE
This warning appears in SummariseCharacteristics

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/PatientProfiles#356]
```
Warning message:
In checkNewName(sexName, x) :
  sex already exists in x, it was renamed to sex_1
```

I think it is due to addDemographics

**Comment by rossdwilliams** [comment]
Hi @catalamarti, I am running into an issue when using the addAge and addSex (also if using addDemographics) where it throws at his warning.

There is an odd issue in one of the studies where when using summariseLargeScaleCharacteristics for age_group and sex strata looking at 

```R
strata = list("sex", "age_group"),
window = list(c(-Inf,-1),c(-365, -31), c(-31, -1))
```

We get results except when looking at the drug_exposure table, in the window c(-31, -1) we only get results for female 65+. in the other windows c(-Inf,-1),c(-365, -31) we get results in all strata. This only happens in one database, in the others we get all results in all strata...

My only thought is that there could be some odd interaction with snowflake causing this. When we run an identical analysis on the condition_occurrence table, we do not get the issue.
