### ISSUE TITLE
Should we allow inf as an upper limit for categories?

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#364]
@catalamarti this will apply to IncidencePrevalence as well, but I'm wondering if you think we should allow a user to put Inf as an upper limit age?

**Comment by edward-burn** [comment]
More generally I think it would be nice to allow Inf in addCategories (e.g. if we want a category of anyone with 365 days or more prior history vs those with less)

**Comment by catalamarti** [comment]
yes, happy with that

**Comment by catalamarti** [comment]
#377

**Comment by catalamarti** [comment]
can you try with this new release?
