### ISSUE TITLE
Think about renaming getConceptName, getStartName, getEndName 

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#366]
I appreciate we need to export these so we can use them as default arguments, but to me the names are a little confusing. For example, getConceptName sounded initially like something would be from CodelistGenerator (like to get the concept name from a concept id).

**Comment by catalamarti** [comment]
startColumn(table), endColumn(table), conceptColumn(table) @edward-burn  ?

**Comment by catalamarti** [comment]
we would need to do this in two releases as DrugUtilisation depends on it

**Comment by catalamarti** [comment]
for the moment it only works for the clinical tables, and you always get the "main concept id": drug_concept_id, condition_concept_id, ...
What do you think? Should we expand the scope?

**Comment by catalamarti** [comment]
to consider if this could be moved into other packages.
For the moment renaming according to @edward-burn suggestion

**Comment by catalamarti** [comment]
#432
