### ISSUE TITLE
addFromConceptSet

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#367]
A nice feature would be to add a new variable based on a concept set. (The way I was doing this in a study was using generateConceptCohortSet and the addCohortIntersectFlag.)

@catalamarti what do you think? This could relate to adding large scale characteristics as well, but this on it's own I think would be a nice function to export.

**Comment by catalamarti** [comment]
something like https://darwin-eu-dev.github.io/DrugUtilisation/reference/summariseCharacteristicsFromCodelist.html but as add? My idea was not to include it, but instead allow using conceptSets from deck (e.g. ICD10, ATC, ...)
Let's think about it
@edward-burn

**Comment by catalamarti** [comment]
#369
