### ISSUE TITLE
Issue with summariseLargeScaleCharacteristics

### ISSUE THREAD

**Issue by pablosg713** [darwin-eu-dev/PatientProfiles#395]
I have the following function definition:

mockSummariseLargeScaleCharacteristics <- function(patient_size = 10, window = list(c(-Inf, -366), c(-365, -31), c(-30, -1), c(1, 30), c(31, 365), c(366, Inf)), eventInWindow = "condition_occurrence", episodeInWindow = "drug_exposure"){
mock <- PatientProfiles::mockPatientProfiles(patient_size=patient_size)
mock$cohort1 |> PatientProfiles::summariseLargeScaleCharacteristics(window = window, eventInWindow = eventInWindow, episodeInWindow = episodeInWindow)
}

Then when I try to run it, ie. by typing

mockSummariseLargeScaleCharacteristics()

I get the following error message:

Error in UseMethod("select") : 
  no applicable method for 'select' applied to an object of class "NULL"

**Comment by MimiYuchenGuo** [comment]
This is caused by PatientProfile mock does not have concept table generated by default, which summariseLargeScaleCharacteristics will need. Do you think we need to add a check in summariseLargeScaleCharacteristics to make sure there is a concept table in cdm? @catalamarti

**Comment by MimiYuchenGuo** [comment]
If you use the mock function in DrugUtilisation it should work:   mock <- DrugUtilisation::mockDrugUtilisation() @pablosg713
