### ISSUE TITLE
issues with copy = TRUE argument in dplyr commands on Snowflake

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#402]
We are seeing a problem with snowflake using the copy = TRUE parameter. Both @cbarbozaerasmus and I have encountered an issue. The error message says table already exists. 

https://github.com/darwin-eu-dev/PatientProfiles/blob/deb422d8384deef0323f9268f7e85ff1b77e3007/R/addIntersect.R#L184

To fix this problem let's explicitly upload any data to the remote datasource (database) before using `left_join`. So basically do the copy step separately and do not used the copy = TRUE argument.

Also we need to add a test for this that runs on snowflake.

**Comment by ablack3** [comment]
I'm creating a PR to fix it. Here is a reprex which I'll add as a new test. I think in general we should avoid the copy = TRUE argument in dplyr and do the copy step ourselves. For example we may need the workarounds implemented in `inSchema` when writing tables.

``` r
library(CDMConnector)
con <- DBI::dbConnect(odbc::odbc(),
                      SERVER = Sys.getenv("SNOWFLAKE_SERVER"),
                      UID = Sys.getenv("SNOWFLAKE_USER"),
                      PWD = Sys.getenv("SNOWFLAKE_PASSWORD"),
                      DATABASE = Sys.getenv("SNOWFLAKE_DATABASE"),
                      WAREHOUSE = Sys.getenv("SNOWFLAKE_WAREHOUSE"),
                      DRIVER = Sys.getenv("SNOWFLAKE_DRIVER"))

cdm_schema <- strsplit(Sys.getenv("SNOWFLAKE_CDM_SCHEMA"), "\\.")[[1]]
write_schema <- strsplit(Sys.getenv("SNOWFLAKE_SCRATCH_SCHEMA"), "\\.")[[1]]

cdm <- cdm_from_con(con, cdm_schema, write_schema)

cdm <- generateConceptCohortSet(cdm, conceptSet = list(gibleed = 192671), name = "cohort1")
#> Error in `generateConceptCohortSet()`:
#> ! cohort1 already exists in the CDM write_schema and overwrite is FALSE!
#> Backtrace:
#>     ▆
#>  1. └─CDMConnector::generateConceptCohortSet(cdm, conceptSet = list(gibleed = 192671), name = "cohort1")
#>  2.   └─rlang::abort(glue::glue("{name} already exists in the CDM write_schema and overwrite is FALSE!"))
cdm <- generateConceptCohortSet(cdm, conceptSet = list(gibleed = 192671), name = "cohort2", requiredObservation = c(1000,0))
#> Error in `generateConceptCohortSet()`:
#> ! cohort2 already exists in the CDM write_schema and overwrite is FALSE!
#> Backtrace:
#>     ▆
#>  1. └─CDMConnector::generateConceptCohortSet(...)
#>  2.   └─rlang::abort(glue::glue("{name} already exists in the CDM write_schema and overwrite is FALSE!"))

result <- cdm$cohort1 %>%
    PatientProfiles::addIntersect(tableName = "cohort2", value = "date") %>%
    dplyr::collect()
#> Error in `checkX()` at PatientProfiles/R/addIntersect.R:75:2:
#> ! x is not a valid table
#> Backtrace:
#>     ▆
#>  1. ├─... %>% dplyr::collect()
#>  2. ├─dplyr::collect(.)
#>  3. └─PatientProfiles::addIntersect(., tableName = "cohort2", value = "date")
#>  4.   └─PatientProfiles:::checkX(x) at PatientProfiles/R/addIntersect.R:75:2
#>  5.     └─cli::cli_abort("x is not a valid table") at PatientProfiles/R/checks.R:20:4
#>  6.       └─rlang::abort(...)
```

<sup>Created on 2023-11-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by edward-burn** [comment]
No worries @ablack3 I think this functionality from dbplyr is generally very nice so am just wondering if there's a way we can get it working consistently across dbms via dbplyr rather than just avoiding it - but if we do then that would be good to know!

**Comment by ablack3** [comment]
``` r
library(CDMConnector)
con <- DBI::dbConnect(odbc::odbc(),
                      SERVER = Sys.getenv("SNOWFLAKE_SERVER"),
                      UID = Sys.getenv("SNOWFLAKE_USER"),
                      PWD = Sys.getenv("SNOWFLAKE_PASSWORD"),
                      DATABASE = Sys.getenv("SNOWFLAKE_DATABASE"),
                      WAREHOUSE = Sys.getenv("SNOWFLAKE_WAREHOUSE"),
                      DRIVER = Sys.getenv("SNOWFLAKE_DRIVER"))


cdm_schema <- strsplit(Sys.getenv("SNOWFLAKE_CDM_SCHEMA"), "\\.")[[1]]
write_schema <- strsplit(Sys.getenv("SNOWFLAKE_SCRATCH_SCHEMA"), "\\.")[[1]]

cdm <- cdm_from_con(con, cdm_schema, write_schema)

cdm <- generateConceptCohortSet(cdm, 
                                conceptSet = list(gibleed = 192671), 
                                name = "cohort1", 
                                overwrite = TRUE)

cdm <- generateConceptCohortSet(cdm, 
                                conceptSet = list(gibleed = 192671), 
                                name = "cohort2", 
                                requiredObservation = c(1000,0),
                                overwrite = TRUE)

result <- cdm$cohort1 %>%
    PatientProfiles::addIntersect(tableName = "cohort2", value = "date") %>%
    dplyr::collect()

# clean up
tables <- list_tables(con, schema = write_schema)
tables_to_drop <- stringr::str_subset(tables, "^cohort[1|2]")

for (tbl in tables_to_drop) {
  DBI::dbRemoveTable(con, inSchema(write_schema, tbl, dbms = "snowflake"))
}

DBI::dbDisconnect(con)
```

<sup>Created on 2023-11-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


Well this was causing the error but now it is not... so.. weird. 

The error message we were getting was something like "table dbplyr_14 already exists"

It is a dplyr issue in the sense that we have not fully tested the copy=TRUE which calls `copy_to`

**Comment by edward-burn** [comment]
Hmmm could this not be about the unique name for temp tables being wrong rather than a problem with this function? (Eg does restarting Rstudio get rid of the error which would suggest this is the case)

**Comment by ablack3** [comment]
Yea I don't. I can't reproduce the error. I'd suggest adding tests on snowflake and other dbms to this package and I'd also suggest not using copy = TRUE. But I can't prove it's a problem unfortunately.

**Comment by ablack3** [comment]
I think I'm going to leave this for now. @cbarbozaerasmus will you paste the screenshot of the error from the data partner in this issue? An error we are not able to reproduce unfortunately.

**Comment by ablack3** [comment]
So I ran the study code and got the error. When I try to isolate it into a small bit of reproducible code I don't get the error though.

**Comment by edward-burn** [comment]
Ok, thanks for looking into it @ablack3. We can indeed work around this in our packages (and I've opened issues on the packages using it), but it would be good to understand what's going on because I imagine copy = TRUE would also frequently appear when users are writing study code (perhaps suggesting we should do https://github.com/darwin-eu-dev/CDMConnector/issues/318 to make something equally intuitive we can point people to use instead)

**Comment by ablack3** [comment]
Basically we need `copy_to` working on all dbms.

**Comment by edward-burn** [comment]
@tiozab fyi
