### ISSUE TITLE
Suggestions for vignette Get cohort intersections

### ISSUE THREAD

**Issue by mderidder95** [darwin-eu-dev/PatientProfiles#409]
Suggestions for function mockPatientProfiles:

- Use more specific names for the cohort tables instead of cohort1 and cohort 2 (which both contain cohort_definition_id 1 and 2). For example 'study_cohort' and 'conditions_cohort'?
- Maybe include only one cohort_definition_id in the study cohort? 
- Assigning specific cohort names to the cohort_definition_ids in the condition cohort would be valuable. Now, for example, a column `cohort_1_m180_to_m1` is created within cohort1 when generating an intersect flag using cohort2 with targetCohortId 1.

Other suggestions:

- Consider arranging the records by cohort_definition_id, subject_id, cohort_start_date (when relevant) before glimpse() to get easier readable output. 
- In the explanation related to `addCohortIntersectCount `is text: "Note that, with the specifications by default, we pick one event (the second one), which is not incident in the window of interest, but overlaps it. Indeed, as the event start date is before the index date in the main cohort and the end date is after it, it is regarded as intersecting."
The second sentence suggests that we are counting events AT index date. I think it should be: 
"Indeed, as the event start date is before the specified window, (here: from 30 days to 1 day before index date in the main cohort) and the end date is within the window or after it, it is regarded as intersecting."

- The last output for discussing `addCohortIntersectCount` does not contain the most important column, namely the counts.
- In paragraph 1.3 Example: `addCohortIntersectDays` function: the code run continues with results from the previous code, which makes the output quite confusing. In `cdm$cohort1TimeTo`, variable `cohort_1_m30_to_m1 ` refers to the previously created count, and variable `cohort_1_0_to_inf` is the new variable with intersect days. Maybe it is better to assign specific column names, e.g., `nameStyle = "{cohort_name}_days_within_{window_name}"`. This would also be valuable information for this vignette. Also, mention that the default window for `addCohortIntersectDays` is (0, Inf).

**Comment by catalamarti** [comment]
vignettes improved
