### ISSUE TITLE
large scale charactersation too big?

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/PatientProfiles#450]
what am I doing wrong?

<img width="714" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/94674809/d716e3bd-d836-4979-b1d9-5854c7d7ea6f">

**Comment by catalamarti** [comment]
You have to use just the summariseLargeScaleCharacteristics this should make it work. Delete the addLargeScaleCharacteristics call.
@tiozab

**Comment by tiozab** [comment]
is that the same for adddrugUuse and addindication as well, can I just not use them and go straigth to summarise?

**Comment by catalamarti** [comment]
Not for the moment but in the next relesse of DrugUtilisation this is the way it will work, add and summarise will be independent

**Comment by tiozab** [comment]
ok, great, I will use this then for now.
