### ISSUE TITLE
what is wrong with my cdm object?

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/PatientProfiles#451]
it does not give this error for the addLargeScaleCharacterisation  but it does give this error for addIndication and addDrugsuse
<img width="517" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/94674809/b6ae1567-2b36-4b17-9498-623f91a83bb3">

**Comment by catalamarti** [comment]
Inc pat is not a cohort, how this object was generated?

**Comment by tiozab** [comment]
<img width="530" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/94674809/ae7f785e-0627-413e-9619-28fb1035a7d1">
it is the patients from the estimate incidence who have an outcome date
it looks like this
<img width="532" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/94674809/58846bd3-c4ed-4f2b-839e-0f4bfd804f48">

how to turn it into a cohort?

**Comment by tiozab** [comment]
using omopgenerics newcohorttable() worked
