### ISSUE TITLE
cohort_definition_id missing

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/PatientProfiles#452]
the inc_pat is a table inserted into cdm coming from the participants function.
I got this error:
<img width="283" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/94674809/8b11bfba-527a-42ef-b4c2-e83ca15f8553">

workaround was to add a mutate transforming the analysis_id from the returnparticipants into a cohort_definition_id
cdm[["inc_pat"]]  %>% mutate(cohort_definition_id = analysis_id) %>%  
  addDemographics(....

**Comment by catalamarti** [comment]
So the problem is that you need a cohort, same for the previous issue. Can you turn you object a cohort?

**Comment by tiozab** [comment]
how? I need to work with the patients that have an outcome_date from the returnParticipants argument and particiapnts function.

**Comment by catalamarti** [comment]
omopgenerics::newCohortTable() will dot it for you

**Comment by tiozab** [comment]
thank you and I will change to omopgenerics 0.0.3

**Comment by tiozab** [comment]
I do not have cohort_definition_ids which seem to be required when establishing a cohort table ?

**Comment by tiozab** [comment]
Found a work around : 
added in inc_pat  a  mutate(cohort_definition_id = analysis_id * i) , now the newCohortTable() function works

<img width="614" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/94674809/5c694e9d-9290-4206-bbf2-829e810309cb">

**Comment by tiozab** [comment]
the addDemographics etc works now, however, when summarising Results, it says my object is not a tibble, but it looks like a tibble

<img width="592" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/94674809/806c9dd7-67aa-44d4-99f0-a39ca767c8c9">

**Comment by tiozab** [comment]
the solution was to use summariseCharacteristics instead ;-)
