### ISSUE TITLE
cumbersome information in summariseCharacteristics

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/PatientProfiles#453]
basically to get my outcome_cohort_name in the table (instead of the number group_level 92 which corresponds to cohort_definition_id 92, I have to do some cumbersome coding in the end) I tried to group_by(outcome_cohort_name) which would be beautiful, but it did not work. 

Moreover, the summariseCharacteristics adds more information than I want, but I cannot make it false, because otherwise I will get nothing = ERROR that i have to fill at least something. Thus, at the end of the code I have to filter the rows that I want to prevent the table from exploding ;-) 

demographics <- cdm[["inc_pat"]]  %>%
            addDemographics(
              age = TRUE,
              ageName = "age",
              ageGroup = list(
                c(0,18),
                c(19,64),
                c(65,150)
              ),
              sex = TRUE,
              sexName = "sex",
              priorObservation = FALSE,
              futureObservation = FALSE,
            ) %>% 
summariseCharacteristics(
  strata = list( "Calendar Year" = "calendar_year"),
  demographics = TRUE,
  ageGroup = list(
    c(0,18),
    c(19,64),
    c(65,150)
  ),
  tableIntersect = list(),
  cohortIntersect = list(),
  conceptIntersect = list(),
  otherVariables = character()
) %>% 
  mutate(cohort_definition_id = as.integer(str_sub(group_level, 8))) %>%
               left_join(cdm[["inc_pat"]] %>% select(cohort_definition_id, outcome_cohort_name) %>% distinct(), by = c("cohort_definition_id"), copy = TRUE ) %>%
  select(-"cohort_definition_id") %>%
  filter(variable_name %in% c("Number subjects","Number records","Age","Sex","Age group"))

**Comment by catalamarti** [comment]
hopefully this will be solved with #497
