### ISSUE TITLE
check indexDate is working properly

### ISSUE THREAD

**Issue by AinaSanchez** [darwin-eu-dev/PatientProfiles#461]

**Comment by edward-burn** [comment]
can we start with a reprex?
- check addLSC and summariseLSC

**Comment by AinaSanchez** [comment]
Hi both,
We made this issue with Martí and I don't recall what exactly was the
problem, if I encounter it again will send a proper replex.

Thank you both,
Aina.

Missatge de Mike Du ***@***.***> del dia dt., 12 de març 2024
a les 13:58:

**Comment by ilovemane** [comment]
@AinaSanchez @catalamarti I am going to close this for now, please reopen if you figure out what the problem was.
