### ISSUE TITLE
Failure with dev duckdb

### ISSUE THREAD

**Issue by krlmlr** [darwin-eu-dev/PatientProfiles#479]
I'm seeing tests failing for this package with the upcoming duckdb 0.10.0. Can you please take a look? I'll follow up with more details.

Easiest to install from r-universe: https://duckdb.r-universe.dev/duckdb# .

We would like to have submitted the duckdb update last week. CRAN will ask if we have notified downstream maintainers early. Are you okay with us claiming that we reached out to you in due time?

Apologies for the short notice. How can I help?

Upstream: https://github.com/duckdb/duckdb-r/issues/75.

CC @hannes @Tmonster.

**Comment by krlmlr** [comment]
See https://github.com/duckdb/duckdb-r/blob/main/revdep/problems.md for the results of our checks.

The error message is: `Error: Cannot compare values of type VARCHAR and type DATE - an explicit cast is required` . Does this ring a bell?

So far, this is the only package where we have seen a regression compared to the last release of duckdb.

**Comment by krlmlr** [comment]
As a workaround, you could run `DBI::dbExecute(con, "SET old_implicit_casting = true")` for your connection. The failure might indicate a subtle problem, though.

**Comment by catalamarti** [comment]
Hi @krlmlr please go ahead with the submision will make sure that new release is compatible with duckdb 0.10.0
