### ISSUE TITLE
should users of patient profiles be calling omopgenerics functions directly?

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#490]
I see this in the documentation 
<img width="831" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/10227522/2109d895-7bfd-4e92-a929-02a30eb20e2e">

But should we have users who are writing studies calling omopgenerics as in this example? does this example code work with a database cdm?

@cebarboza

**Comment by catalamarti** [comment]
No, this will be addressed here #508
