### ISSUE TITLE
Allow for any quantile in summarizeResult

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#512]
Would it be possilbe to allow users to specify any quantiles they want in summarizeResult and not be restricted to multiples of 5?

<img width="941" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/10227522/506bc176-3946-46c5-9c66-9471a9dd6dd1">

**Comment by catalamarti** [comment]
this should already be implemented in the development version #478
