### ISSUE TITLE
Clarify qXX meaning

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#522]
I don't think it is particularly clear what qXX means here
```
Whether to display the exact quantiles that can be computed or only the qXX to summarise all of them
```

https://github.com/darwin-eu-dev/PatientProfiles/blob/48532315efa1e8df723f04cdd49f486f75870a95/R/formats.R#L111

**Comment by catalamarti** [comment]
should be clarified with the new documentation, please reopen otherwise
