### ISSUE TITLE
Flexibility around compute behaviour

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#530]
@catalamarti To think about, but it would be nice if the user can have some control over the compute behaviour inside add* functions so that they could choose between 1) computing to a permanent table, 2) computing to a temporary table, or 3) not computing at all (eg so that show_query can be passed afterwards)

It's a more general issue that just for this but we could probably start be thinking about it in this context.

**Comment by catalamarti** [comment]
that would be ideal, but I dont know if for addCohortIntersectCount would be a good option for example, we need some computes inside I think

**Comment by catalamarti** [comment]
add a `name = NULL` argument to functions that produce a temporary table. If name is a character then a permanent table with that name will be produced.

**Comment by edward-burn** [comment]
default - from global environemt?
change to NULL - temporary
change to character - permanent (table name that is given)?

**Comment by edward-burn** [comment]
More ideas to discuss

```
cdm$cohort <- cdm$cohort |> 
  addAge(name = NULL) # temporary
cdm$cohort <- cdm$cohort |> 
  addAge(name = "cohort") # cohort - overwrites
cdm$new_cohort <- cdm$cohort |> 
  addAge(name = "new cohort") # new_cohort - new table called "new_cohort"

cdm$new_cohort <- cdm$cohort |> 
  addAge(name = tableName(x))

cdm$new_cohort <- cdm$cohort |> 
  addAge(name =  getOption("overwrite", 1)) 
```

**Comment by catalamarti** [comment]
#668 #667
