### ISSUE TITLE
window default: -inf to inf

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#532]
@catalamarti at the moment the default window for cohort intersection (and similar functions) is 0 to Inf,
https://github.com/darwin-eu-dev/PatientProfiles/blob/6c1476a57dc628093d4e000cc4358844981dc10f/R/addCohortIntersect.R#L67

I´m wondering if this default should not be -Inf to Inf, so as to be broadest possible?

**Comment by catalamarti** [comment]
mmmmmmmmm this would be a breaking change I think, if possible I would like to avoid changing the default. but happy to discuss

**Comment by edward-burn** [comment]
Yes, I see that. Happy to leave as is. Another option would be to have no default, especially as this is likely to vary a lot and we want people to think about what they want https://design.tidyverse.org/required-no-defaults.html

**Comment by catalamarti** [comment]
To consider removing the default for:
- `window`
- `order`
