### ISSUE TITLE
test-AddConceptIntersect.R is currently empty

### ISSUE THREAD

**Issue by xihang-chen** [darwin-eu-dev/PatientProfiles#545]

**Comment by edward-burn** [comment]
Also low code coverage for addTableIntersect. @catalamarti can we prioritise adding tests to these two functions?

![image](https://github.com/darwin-eu-dev/PatientProfiles/assets/9583964/89b2cc0f-7f95-4023-a37d-d082653cace3)

**Comment by edward-burn** [comment]
I think even some rudimentary tests on input validation and output (e.g. with eunomia could still be valuable)

**Comment by catalamarti** [comment]
happy if someone want to add some tests with eunomia :)

**Comment by catalamarti** [comment]
#575
