### ISSUE TITLE
should summarize result download the full cohort table before summarizing or should it summarize the data in the database?

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#548]
Usually database operations are faster when working with large datasets like summarizing a cohort table for example.

Summarize result downloads person level data and summarizes it in R as far as I can tell. 

i imagine there could be cases where a cohort table is too large to download into R. Also database side summarization should be faster, epecially for large cohort tables. 

What do you all think about summarizing in the database (i.e. using summarizeQuantile for example)?

**Comment by edward-burn** [comment]
until all functionality is supported on the db side, I think we can start with #634
