### ISSUE TITLE
summariseResult has trouble detecting numeric vs binary

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#562]
I have a dataset with a bunch of flags on it. These variables are 1 or 0 and when I collect the data into R the come in as integers. 
However summarizeResult seems to thing they are numeric and so it won't allow me to summarize them using count or percentage which is what I need.

<img width="1192" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/10227522/19a7f92f-4aaa-43af-a1e4-370b222528d3">

**Comment by ablack3** [comment]
@edward-burn @catalamarti 
DatabaseConnector does not really support logical types though so if people use DatabaseConnector (which they really want to do) then they will not be able to create binary variables I don't think. Should consider allowing binary variables to be 1 or 0?

**Comment by ablack3** [comment]
I also got an error when I tried using logical types

I have a table with logical values in columns.
![image](https://github.com/darwin-eu-dev/PatientProfiles/assets/10227522/c95d1ec6-d024-4a96-a2d7-b105fad5896e)

when I call summarizeResult I get a sql error.

![image](https://github.com/darwin-eu-dev/PatientProfiles/assets/10227522/ac00af14-8477-4e93-abd6-54eb84b6e8de)

So I think I need to just write some dplyr to do the summarization step for the study.

**Comment by ablack3** [comment]
workaround -- sumarize flags as 1 or 0 using mean and sum... then rename them to percentage and count. :)

**Comment by ablack3** [comment]
I think there is some issue here. maybe the problem is that I have like 20 or more indicator variables I'm summarizing.

**Comment by catalamarti** [comment]
Have you tried with the behavior of the development version? @ablack3

**Comment by catalamarti** [comment]
Now this should be fixed in #604
