### ISSUE TITLE
mirror this repo in darwin-eu (public repo) and create github releases that match cran releases.

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#567]
Can we create releases on github so we have stable tags we can use to get the source code from a specific version/release.

Also I think we should mirror all the darwin repos in both darwin-eu-dev and darwin-eu since this was our plan. We can change the plan but until then let's follow what we decided on (mirrored repos).

just add a new git remote and push the latest release to it. 

https://github.com/darwin-eu/PatientProfiles

**Comment by catalamarti** [comment]
I would prefer to move the whole repo to darwin-eu
what do you think @edward-burn

**Comment by catalamarti** [comment]
any thoughts @edward-burn @ablack3 ? I would prefer to work in only one repo, otherwise things gets messy

**Comment by ablack3** [comment]
@rossdwilliams can we all align on our github process and update our documentation?

@catalamarti Will you at least create tags for each release on github? This let's us easily install older versions. CRAN does not keep all old versions forever so the release tags are important.

**Comment by catalamarti** [comment]
hi @ablack3 you can install older version of packages using:
```
install.packages("http://cran.r-project.org/src/contrib/Archive/PatientProfiles/PatientProfiles_0.6.0.tar.gz", repos=NULL, type="source")
```

As you can see all versions are available here:
https://cran.r-project.org/src/contrib/Archive/PatientProfiles/

Next release will probably be 1.0.0 and then we will start tagging

**Comment by rossdwilliams** [comment]
Hi @ablack3 which processes are we not aligned on? I can make sure documentation for this is clear and up to date.

All cran releases should have a github tag aswell so we can easily track them.

@catalamarti it will probably be? or it will be? do you have a plan or a roadmap to a v1.0.0 release anywhere so that we can plan around that?

**Comment by catalamarti** [comment]
As I explained in my training a couple of weeks ago, the plan for PatientProfile was first to split it out into this package and CohortCharacteristics. This has been done and now, as I´m sure you can see, we are working hard to incorporate user feedback into PatientProfiles so as to do a version 1.0 stable release (i.e. that is no longer experimental, as it is clearly tagged as now). We hope to release this stable version within the next couple of weeks.

**Comment by ablack3** [comment]
> Hi @ablack3 which processes are we not aligned on?

I'm not clear if we are mirroring repos between darwin-eu-dev and darwin-eu github orgs. I think the current process is if a repos is public in darwin-eu-dev then it is not mirrored in darwin-eu so we have some repos that only exist in darwin-eu-dev. 
https://github.com/darwin-eu/visOmopResults only exists in darwin-eu although I think the plan might be to have it in both.

The other process is creating release tags. Some repos have them but others do not. I think it is helpful because then you have a copy of the source code. The tarball Mari pointed to isn't exactly the same as the snapshot of the github repo - e.g. I'm not sure it includes anything listed in .Rbuildignore. I also don't know if those archives will be there a year from now.

Anyway it would be helpful to have a constant approach to mirroring (darwin-eu-dev, darwin-eu) and tagging.

**Comment by ablack3** [comment]
> incorporate user feedback

@catalamarti do you record user feedback and are you getting much feedback from the Erasmus developers on PP?

**Comment by rossdwilliams** [comment]
> > Hi @ablack3 which processes are we not aligned on?
> 
> I'm not clear if we are mirroring repos between darwin-eu-dev and darwin-eu github orgs. I think the current process is if a repos is public in darwin-eu-dev then it is not mirrored in darwin-eu so we have some repos that only exist in darwin-eu-dev. https://github.com/darwin-eu/visOmopResults only exists in darwin-eu although I think the plan might be to have it in both.
> 
> The other process is creating release tags. Some repos have them but others do not. I think it is helpful because then you have a copy of the source code. The tarball Mari pointed to isn't exactly the same as the snapshot of the github repo - e.g. I'm not sure it includes anything listed in .Rbuildignore. I also don't know if those archives will be there a year from now.
> 
> Anyway it would be helpful to have a constant approach to mirroring (darwin-eu-dev, darwin-eu) and tagging.

this is detailed in our gitflow document, i will share the link with you. Darwin packages should be cdeveloped in Darwin-eu-dev github and then upon release and version should be moved to the darwin-eu github which is more public facing (e.g. external non-darwin parties that want to use darwin code should use the darwin-eu as the source and not darwin-eu-dev. Darwin-eu github should contain only a main branch and have no active development on it. 

If this process is not being followed then it is something we should discuss as a team.

**Comment by ablack3** [comment]
We will discuss this at the next meeting in oxford.
