### ISSUE TITLE
Is changing the output format and column names of a function considered a breaking change?

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#568]
I think changing the output format (e.g. "estimate_name" pp 0.5 vs "estimate_type" pp v0.6) might be considered a breaking change. It definitely breaks my study code. 

I'm looking at the output or summariseResult between version 0.5 and 0.6 of patient profiles.

Are breaking changes allowed before we reach v1.0?

Just trying to understand what to expect in terms of stability of output formats.

@cebarboza for awareness on reportgenerator. 

report generator heavily relies on column names of output.

In PP v-0.6
<img width="558" alt="image" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/10227522/05ee9672-5235-4e43-87ea-bb7f2715aba4">

and in pp v0.5 we have "count" and "percentage in the estimate type column.

**Comment by catalamarti** [comment]
hi @ablack3 @cebarboza so `estimate_type` is restricted to: `omopgenerics::estimateTypeChoices()`, whereas estimate_name is a free field where you put a name that is more descriptive of the estimate.
We export everything as character so estimate_type allows us to recover the type.
The goal is to do small modifications on it, but we always make the dependent functions to keep working (e.g. tableCharacteristics will always work with the output of summariseCharacteristics)
