### ISSUE TITLE
Issue with cohort set validation

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#569]
I'm running some code on ipci so I don't have a reprex. But I'll describe the issue. I'm using the latest release of patient profiles and using the addConceptIntersect function. I have a cohort table that passes omopgenerics::validatGeneratedCohortSet.

I then use add future observation with patient profiles, and then run omopgenerics::validateGeneratedCohortSet and I get an error about incosistant naming. So adding future observation makes the cohort no longer valid.

If I take a valid cohort set and then run patientProfiles::addConceptIntersect() and then run omopgenerics::validateGeneratedCohortSet I also get an error about overlapping cohort entries. I would not expect that adding a concept intersect date or count would create overlapping cohort entries.

My issue is that I need to call compute after adding these and now dplyr::compute is dispached to omopgenerics which runs validateGeneratedCohortSet on the table giving me this error. So I can't call compute on a cohort that has been modified with addObservation or addConceptIntersect. 

When I have time I'll try to create a reprex.

**Comment by catalamarti** [comment]
To be handled in the new version of addConceptIntersect

**Comment by catalamarti** [comment]
#575
