### ISSUE TITLE
use internal function to also plotCohortTimming and plotCohortOverlap

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/PatientProfiles#573]

**Comment by catalamarti** [comment]
to take into account: `omopgenerics::estimateTypeChoices()`

**Comment by MimiYuchenGuo** [comment]
omopgenerics::estimateTypeChoices()
[1] "numeric"    "integer"    "date"       "character"  "proportion" "percentage" "logical"   

change all estimate_value to numeric, except "date" and "logical"

**Comment by MimiYuchenGuo** [comment]
![image](https://github.com/darwin-eu-dev/PatientProfiles/assets/57181081/58d6d5f9-afab-4983-8be0-84de52a30392)
current output with plotfunciton.
1. do we want to remove the 0 percentage?
2. i assume the use of tidy function from visomopresult is used to get uniqueCombination only but then I manually added back group_level for those unique combination and use group_level as yAxis and estimate_value as xAxis for that plot.

**Comment by MimiYuchenGuo** [comment]
![image](https://github.com/darwin-eu-dev/PatientProfiles/assets/57181081/c9370b7e-a7f6-4012-9c2e-42bcb5d93652)
boxplot (plotcohorttiming) using the plotFunction

**Comment by MimiYuchenGuo** [comment]
For a summarised cohort intersect like this: <img width="571" alt="Screenshot 2024-04-03 at 15 19 18" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/57181081/2d500966-08af-4635-ae20-981adab0a8b4">
the plot is a barplot like this (depend on which axis is numeric, it is horizontal or vertical:
![image](https://github.com/darwin-eu-dev/PatientProfiles/assets/57181081/67719271-1fe7-4900-bff9-f56f6cd0f2a8)

**Comment by catalamarti** [comment]
Done! thanks @MimiYuchenGuo
