### ISSUE TITLE
plotCharacteristics

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/PatientProfiles#574]
- `variable_name` it is compulsory to face by it (unless there is only one variable_name
- Do not throw error when colorvar or facetvar not given :)
- change to facetY default "group_level", "strata_level" facetX default "variable_name" (https://ggplot2.tidyverse.org/reference/facet_grid.html)

**Comment by MimiYuchenGuo** [comment]
we agreed that barplot needs to plot percentage unless the variable_name does not have percentages, eg. number_subjects

**Comment by MimiYuchenGuo** [comment]
<img width="404" alt="Screenshot 2024-03-28 at 12 22 39" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/57181081/11cf0159-458b-4a6a-9ff5-64994915139a">
strata_level for all age group is overall but variable level is different, which variable to color by or facet by???

**Comment by MimiYuchenGuo** [comment]
what should be the default xAxis and yAxis? originally i set xAxis default to varialble_name, but then you requested facetX by "variable_name" always as default

**Comment by MimiYuchenGuo** [comment]
<img width="884" alt="Screenshot 2024-03-28 at 12 37 10" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/57181081/3224590e-0042-4f4d-af60-eb1db550e1f2">
If facetX by variable_name, even if I set scaly_y as free won't work as there will be a prior history very high in every row. but set facetY as variable_name it's fine

<img width="404" alt="Screenshot 2024-03-28 at 12 22 39" src="https://github.com/darwin-eu-dev/PatientProfiles/assets/57181081/66eb9071-6ea1-41c8-a3f3-1ab945c4c3a8">

**Comment by MimiYuchenGuo** [comment]
removed facetOrder options and colorNames parameter for now
