### ISSUE TITLE
summariseCohortOverlap - why include number of records and why to proportions differ for subjects vs records?

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#586]
@nmercadeb @catalamarti I'm not sure I unerstand why cohort overlap has number of subjects and number of records (with the proportions being different). As I understand it the point of cohort overlap is just to say if someone is only in cohort X, only in cohort Y, or both cohort X and Y. So it seems only relevant at the person level and so I would have just expected to number of subjects

![image](https://github.com/darwin-eu-dev/PatientProfiles/assets/9583964/55ee1d39-0440-4f26-8fd6-3aeec3cac911)

**Comment by edward-burn** [comment]
``` r
library(CDMConnector)
library(CodelistGenerator)
library(PatientProfiles)
library(dplyr)
#> Warning: package 'dplyr' was built under R version 4.2.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.2.3

con <- DBI::dbConnect(duckdb::duckdb(),
                      dbdir = CDMConnector::eunomia_dir())
cdm <- CDMConnector::cdm_from_con(con,
                                  cdm_schem = "main",
                                  write_schema = "main", 
                                  cdm_name = "Eunomia")

meds_cs <- getDrugIngredientCodes(cdm = cdm, 
                                  name = c("acetaminophen",
                                           "amoxicillin",
                                           "aspirin",
                                           "heparin",
                                           "morphine",
                                           "oxycodone",
                                           "warfarin"))

cdm <- generateConceptCohortSet(
  cdm = cdm,
  name = "meds",
  conceptSet = meds_cs,
  end = "event_end_date",
  limit = "all",
  overwrite = TRUE
)

meds_overlap <- cdm$meds |> 
  summariseCohortOverlap()

# tableCohortOverlap(meds_overlap)
```

<sup>Created on 2024-03-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by nmercadeb** [comment]
Is the number of overlap records for each person, say in cohort X a person has 3 entries, and 5 in cohort Y, the overlap number of records would be 3.
It was in the original function in CohortContext, and I kept it since I thought this could be helpful when revising cohort phenotypes? but happy to remove this if you think it does not make sense!

**Comment by edward-burn** [comment]
I think it is a bit strange (and I can say that if I originally did that!). I would prefer we just do it at the person level as I think that it is more intuitive for everyone
