### ISSUE TITLE
Feature request addDateofDeath  function

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#616]
how about addDateOfDeath  in addition to addDateOfBirth?

**Comment by catalamarti** [comment]
I am happy to add this, any thoughts @edward-burn @ilovemane ? Should we add it also in addDemographics?

**Comment by catalamarti** [comment]
I am happy to include in PatientProfiles:
```
addDeathDate/Flag/Days(
  x,
  indexDate = "cohort_start_date",
  window = c(0, Inf),
  nameStyle = "death_date/flag/days"
)
```
would that work for you @ablack3 @edward-burn ?

**Comment by edward-burn** [comment]
Sounds good to me!

**Comment by catalamarti** [comment]
@ilovemane are you happy to take care of this?
