### ISSUE TITLE
Include all zeros in summarizeResult output

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#619]
Two PIs have requested that the output from SummarizeResults contains all results for all strata with explicit zeros. the current behavior is to leave zeros out of the output.

**Comment by catalamarti** [comment]
this was considered in #275, but at the end it was not prioritised, I think that for the moment I feel more comfortable summarising whats on the data than trying to add 0 to things that the user may not want.
When you built tableCharacteristics  or tableLargeScaleCharacterisation these are reported as "-", that would be the equivalent to 0

**Comment by ablack3** [comment]
Yea and it makes the result set much larger. ok.
