### ISSUE TITLE
considering changing a couple lines of codes that uses endDateColumn

### ISSUE THREAD

**Issue by xihang-chen** [darwin-eu-dev/PatientProfiles#642]
Since it can no longer output NA, we may consider enhancing the codes accordingly.

For example: 
1. https://github.com/darwin-eu-dev/PatientProfiles/blob/main/R/addConceptIntersect.R#L195C1-L198C8
2. https://github.com/darwin-eu-dev/PatientProfiles/blob/main/R/summariseLargeScaleCharacteristics.R#L417 (this is more on CohortCharacteristics side)

**Comment by catalamarti** [comment]
#641
