### ISSUE TITLE
`ageDefaultMonth/Day` -> `ageMissingMonth/Day` ?

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/PatientProfiles#652]
https://darwin-eu-dev.github.io/PatientProfiles/reference/addDemographics.html @edward-burn

**Comment by edward-burn** [comment]
@catalamarti we can possibly have a look at the four arguments
-   ageDefaultMonth = 1,
-   ageDefaultDay = 1,
-   ageImposeMonth = FALSE,
-   ageImposeDay = FALSE,

Both in terms of naming, but also whether they are necessary to have at all. If people really want this level of customisation they can always edit the person table fields themselves.

**Comment by catalamarti** [comment]
- `ageDefaultMonth/Day` -> `ageMissingMonth/Day`
- deprecate: ageImposeMonth, ageImposeDay
