### ISSUE TITLE
support regimen domain in addConceptIntersectFlag and similar functions

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/PatientProfiles#676]
The regimen domain is not supported so when PIs create concept sets where one of the included concepts is a regimen the code gives an error. One approach is just to remove these concepts in the study code or in Atlas. We could also add this domain to PatientProfiles.

Only data partners with OMOP CDM v5.4 will have these concepts. In my current study some DPs have 5.3 and others have 5.4 so the code needs to adapt based on the version of the omop cdm.

**Comment by nmercadeb** [comment]
I looked into supporting regimen, but the only place where I found concepts from this domain being used is in the "episode_object_concept_id" column of the episode table (https://ohdsi.github.io/CommonDataModel/cdm54.html#episode). 

I have added support for the episode domain, which we did not have before (PR #678 ), but I'm unsure if this resolves it @ablack3

**Comment by ablack3** [comment]
Thank @nmercadeb. Yes I think it should work. We need to make sure that if the database does not have the regimen table because the cdm version is 5.3 then the code does not give an error but just silently ignores those concepts.
