### ISSUE TITLE
different behavior addCdmName and addCohortName

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/PatientProfiles#680]
If the column already exists:
- `addCdmName` overwrites it
- `addCohortName` two resultant columns are created: `cohort_name.x` and `cohort_name.y`

what behavior do we want?

**Comment by xihang-chen** [comment]
I think overwrite for addCohortName() makes more sense. Although I think it could be nice to throw an warning that it has been overwritten.

A user that uses these functions probably don't know these columns already exist in their data frame so I think overwrite is fine. Plus I don't think cohort_name.x and cohort_name.y are informative column names.

**Comment by catalamarti** [comment]
agreed
