### ISSUE TITLE
Allow for multiple dates to be passed 

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#78]
It would be nice if we could do something like the below:

```
cdm$condition_occurrence <- cdm$condition_occurrence  %>% 
  addAge(cdm = cdm, ageAt = c("condition_start_date", "condition_end_date")
```

Noting that we'd also need to change the names to something like age_condition_start_date and age_condition_end_date.

**Comment by edward-burn** [comment]
On second thoughts maybe this needs a bit more discussion @catalamarti. If we decided add* functions always return only one column this would make things simpler for both development and less open to misunderstanding by users (and users could always call functions multiple times)

**Comment by catalamarti** [comment]
I agree that the one column restriction will simplify things but, If we do this it is massive efficiency issue for AddCohortIntersect @edward-burn

**Comment by edward-burn** [comment]
Yes indeed, if (and only if) we decided that was the rule for add* functions then I wouldn´t apply in to cohort intersect but rather change it´s name to indicate that it is a different concept to a simple addAge, addSex, etc

**Comment by catalamarti** [comment]
I think the way the package moved is not sth that we are considering now.
can we close this @edward-burn ?
